import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FBadgeStyles statusBadgeStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final primaryTextStyle = typography.body.xs.copyWith(color: Colors.blue, fontWeight: .w500);
  final primaryDecoration = ShapeDecoration(
    shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.pill),
    color: Colors.blue.withValues(alpha: colors.brightness == .light ? 0.1 : 0.2),
  );
  final secondaryTextStyle = typography.body.xs.copyWith(color: Colors.grey, fontWeight: .w500);
  final secondaryDecoration = ShapeDecoration(
    shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.pill),
    color: Colors.grey.withValues(alpha: colors.brightness == .light ? 0.1 : 0.2),
  );
  final destructiveTextStyle = typography.body.xs.copyWith(color: Colors.red, fontWeight: .w500);
  final destructiveDecoration = ShapeDecoration(
    shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.pill),
    color: Colors.red.withValues(alpha: colors.brightness == .light ? 0.1 : 0.2),
  );
  final outlineShape = RoundedSuperellipseBorder(
    side: BorderSide(color: colors.border, width: style.borderWidth),
    borderRadius: style.borderRadius.pill,
  );
  final padding = touch
      ? const EdgeInsets.symmetric(horizontal: 12, vertical: 6)
      : const EdgeInsets.symmetric(horizontal: 10, vertical: 6);
  return FBadgeStyles(
    .from(
      FBadgeStyle(
        decoration: ShapeDecoration(
          shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.pill),
          color: colors.primary,
        ),
        contentStyle: FBadgeContentStyle(
          labelTextStyle: typography.body.xs.copyWith(
            color: colors.primaryForeground,
            fontWeight: .w500,
          ),
          padding: padding,
        ),
      ),
      variants: {
        [.primary]: FBadgeStyle(
          decoration: primaryDecoration,
          contentStyle: FBadgeContentStyle(labelTextStyle: primaryTextStyle, padding: padding),
        ),
        [.secondary]: FBadgeStyle(
          decoration: secondaryDecoration,
          contentStyle: FBadgeContentStyle(labelTextStyle: secondaryTextStyle, padding: padding),
        ),
        [.destructive]: FBadgeStyle(
          decoration: destructiveDecoration,
          contentStyle: FBadgeContentStyle(labelTextStyle: destructiveTextStyle, padding: padding),
        ),
        [.outline]: .delta(
          decoration: .shapeDelta(shape: outlineShape, color: colors.card),
          contentStyle: .delta(labelTextStyle: .delta(color: colors.foreground)),
        ),
      },
    ),
  );
}
